version: "3.9"

services:
  server:
    env_file:
      - .env
    container_name: "tonify-server"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SECURE_SERVER_PORT}:${SECURE_SERVER_PORT}"
