version: "3.9"

services:
  server:
    env_file:
      - .env
    container_name: "tonify-server"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - my_network
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SECURE_SERVER_PORT}:${SECURE_SERVER_PORT}"
    depends_on:
      - database
  database:
    container_name: "tonify-db"
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_HOST=tonify-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pa55word
      - POSTGRES_DB=tonify
      - POSTGRES_MODE=disable
    networks:
        - my_network
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  data: