CREATE TABLE IF NOT EXISTS task (
    id SERIAL PRIMARY KEY,
    owner_id INT NOT NULL,
    title VARCHAR(512) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES account(id) ON DELETE CASCADE
);